In [2]:
import numpy as np

In [3]:
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [17]:
my_array2 = np.array([1,2,3,4])
my_array3 = np.array([[1,2,3], [1,2,3]])
print(my_array2)
print(my_array3)

[1 2 3 4]
[[1 2 3]
 [1 2 3]]


In [22]:

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.zeros((2,2), dtype = np.int16)

array([[0, 0],
       [0, 0]], dtype=int16)

In [34]:
np.random.random ((2,2))

array([[0.68838975, 0.18501669],
       [0.02596335, 0.02787579]])

In [42]:
np.empty((2,2))

array([[0.00000000e+000, 0.00000000e+000, 6.94664816e-310,
        6.94664629e-310, 2.37151510e-322]])

In [43]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [44]:
np.full((2,2), 2)

array([[2, 2],
       [2, 2]])

In [45]:
np.arange(10,25,5)

array([10, 15, 20])

In [46]:
np.arange(10,25,2)

array([10, 12, 14, 16, 18, 20, 22, 24])

In [47]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [49]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [50]:
np.linspace(1,2,2)

array([1., 2.])

In [51]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [52]:
print(len(my_array))

2
